FROM python:3.11-slim-buster

# Dependencies for opencv.
RUN apt-get update && apt-get install -y \
    libgl1-mesa-dev \
    libglib2.0-0

WORKDIR /usr/src/app

COPY .streamlit /usr/src/app/.streamlit
COPY data /usr/src/app/data
COPY docs /usr/src/app/docs
COPY webui /usr/src/app/webui
COPY requirements.txt /usr/src/app/requirements.txt

RUN pip install -r requirements.txt

# Ensure the latest version of maps4fs is installed.
RUN pip install --upgrade maps4fs

COPY favicon.png /usr/local/lib/python3.11/site-packages/streamlit/static/favicon.png
RUN sed -i 's|<noscript>.*</noscript>|<noscript>Generate map templates for Farming Simulator from real places in a couple of clicks. Get the realistic terrain, roads, rivers, fields, and more. Completely free and open-source.</noscript>|' /usr/local/lib/python3.11/site-packages/streamlit/static/index.html
RUN sed -i 's|<title>.*</title>|<title>maps4FS</title>|' /usr/local/lib/python3.11/site-packages/streamlit/static/index.html

EXPOSE 8501

ENV PYTHONPATH .:${PYTHONPATH}
ENV LITEVERSION True
CMD ["streamlit", "run", "./webui/webui.py"]