name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install osmnx from forked repo
        run:  pip install git+https://github.com/iwatkot/osmnx.git

      - name: Install dependencies
        run:  pip install -r dev/requirements.txt

      - name: Install zip utility
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Clone maps4fsdata and prepare data
        run: |
          git clone --depth 1 https://github.com/iwatkot/maps4fsdata.git /tmp/maps4fsdata
          cd /tmp/maps4fsdata
          chmod +x prepare_data.sh
          ./prepare_data.sh
          cp -r data $GITHUB_WORKSPACE/data
          rm -rf /tmp/maps4fsdata

      - name: Run mypy to generate cache
        run: mypy maps4fs || true

      - name: Install missing stub packages
        run: mypy --install-types --non-interactive

      - name: Run mypy
        run: mypy maps4fs

      - name: Run pylint
        run: pylint maps4fs

      - name: Run pytest with coverage
        run: pytest -v --cov=maps4fs --cov-report xml --junit-xml=report.xml

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: pytest results
          path: report.xml
          reporter: java-junit

      - name: Test summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: report.xml
          show: "all tests"

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: iwatkot/maps4fs